name: lambda-function
on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        description: "Package Name which after Gradle build will be located in build"
        required: true
        type: 'string'
      FUNCTION_NAME:
        description: "AWS Lambda Function Name"
        required: true
        type: 'string'
      AWS_REGION:
        description: "AWS Region which the ECR is located"
        required: true
        type: 'string'
      ENVIRONMENT:
        description: "Environment to be deployed"
        required: true
        type: 'string'

permissions:
  id-token: write
  contents: read
  deployments: write
  statuses: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.ENVIRONMENT }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Setup Amazon Coretto 17
        uses: actions/setup-java@v4
        with:
            distribution: 'corretto'
            java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
          GITHUB_ACTOR: ${{ secrets.GH_PACKAGES_ACTOR }}
      - name: Assume deploy role
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-region: ${{ inputs.AWS_REGION }}
            role-to-assume: ${{ secrets.AWS_LAMBDA_DEPLOY_ROLE }}
            role-duration-seconds: 1200
      - name: deploy
        uses: donaldpiret/lambda-deploy@master
        with:
          package: ${{ inputs.PACKAGE_NAME }}
          function-name: ${{ inputs.FUNCTION_NAME }}
